### PR TITLE
audio: add support for static sources, add lua_ref logic to playing sounds

### PR DESCRIPTION
**Pull request by jstine35**
- avoids cutting sounds before they finish playing
 - cleans up memory for sources
 - even closes file handles

**Intended as a fix for Issue #163**

### CODE REVIEW

**Comment by jstine35** [comment]
I'm doing a major revamp of this PR, hopefully should have it wrapped up in a day or two.

**Comment by jstine35** [comment]
@kivutar New rewrite is complete. Scope fo the PR changed, so I edited the title accordingly.

Needs a little bit more testing. I tested mostly slambug.lua with static and streaming versions of both ogg and wav data.

**Comment by RobLoach** [comment]
Just tested loading a music.ogg file, and played it successfully. Didn't crash on quit, but I didn't do lots testing on it to stop and play again.

**Review by kivutar — CHANGES_REQUESTED** [review]
I'm still noticing 2 issues on this branch after testing a game:

 - some 16 wav are crackling at the end
 - got this assertion failed in lutro_audio_deinit when quiting:

```
kivutar@macbookpro ~/ludo master % ./ludo -L ~/lutro/lutro_libretro.dylib ~/pieblaster
2021/03/17 11:18:16 [OpenAL]: Using 4 buffers of 8192 bytes.
2021/03/17 11:18:16 [Core]: Game loaded: /Users/kivutar/pieblaster
Found 1 leaked audio source references. Was lua_close() called first?
Assertion failed: (false), function lutro_audio_deinit, file audio.c, line 255.
SIGABRT: abort
PC=0x7fff202f2462 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x43c3e10, 0xc000acfe60, 0x416f3f30)
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/cgocall.go:133 +0x5b fp=0xc000acfe30 sp=0xc000acfdf8 pc=0x4008d3b
github.com/libretro/ludo/libretro._Cfunc_bridge_retro_deinit(0x416f3bb0)
	_cgo_gotypes.go:354 +0x45 fp=0xc000acfe60 sp=0xc000acfe30 pc=0x42ab125
github.com/libretro/ludo/libretro.(*Core).Deinit.func1(0xc004154000)
	/Users/kivutar/ludo/libretro/libretro.go:399 +0x56 fp=0xc000acfe98 sp=0xc000acfe60 pc=0x42aea56
github.com/libretro/ludo/libretro.(*Core).Deinit(0xc004154000)
	/Users/kivutar/ludo/libretro/libretro.go:399 +0x2f fp=0xc000acfeb0 sp=0xc000acfe98 pc=0x42ad40f
github.com/libretro/ludo/core.Unload()
	/Users/kivutar/ludo/core/core.go:210 +0x4a fp=0xc000acfed0 sp=0xc000acfeb0 pc=0x438ad4a
main.main()
	/Users/kivutar/ludo/main.go:132 +0x52a fp=0xc000acff88 sp=0xc000acfed0 pc=0x43aea4a
runtime.main()
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/proc.go:204 +0x209 fp=0xc000acffe0 sp=0xc000acff88 pc=0x403cce9
runtime.goexit()
	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000acffe8 sp=0xc000acffe0 pc=0x406ec21

goroutine 36 [chan receive]:
github.com/libretro/ludo/core.Init.func1(0xc000101db0)
	/Users/kivutar/ludo/core/core.go:37 +0x5a
created by github.com/libretro/ludo/core.Init
	/Users/kivutar/ludo/core/core.go:36 +0x67

rax    0x0
rbx    0x101a3e00
rcx    0x7ffeefbff678
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbff6a0
rsp    0x7ffeefbff678
r8     0xff
r9     0xcccccccccccccccd
r10    0x101a3e00
r11    0x246
r12    0x307
r13    0x39717000
r14    0x6
r15    0x16
rip    0x7fff202f2462
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
```

**Comment by jstine35** [comment]
WAV decoding is now fixed, no more static at the end of samples.

I wasn't able to reproduce the assert on close yet, and it's a non-issue (leaking at exit hardly matters) so I just commented it out for now. There's a possibility it's not even a bug, and that Lua GC is just not cleaning things up as expected.

**Review by kivutar — APPROVED** [review]

**Pull request merged**
