### PR TITLE
Disable luasocket

### PR DESCRIPTION
**Pull request by RobLoach**
It has been causing strange segment faults.

@CoalaJoe Mind testing this out?

### CODE REVIEW

**Comment by CoalaJoe** [comment]
I tested it. 
The compilation was successful on OSX. But I still can't get to run the tests.
`Segmentation fault: 11`

Here is the full trace: http://pastebin.com/Ue2g67qx

**Comment by CoalaJoe** [comment]
Anyway. Your PR is mergeable, it does what it says.

Any idea what's wrong for OSX?

**Comment by RobLoach** [comment]
If it's still segfaulting, not sure. @Kivutar, have you run into this?

**Comment by Kivutar** [comment]
I remember that it was not segfaulting in my Arch and in Lakka. But there is certainly something wrong with the code.

**Comment by RobLoach** [comment]
Going to close this one. Thanks!

**Pull request closed without merging**
