### PR TITLE
Add LuaSocket

### PR DESCRIPTION
**Pull request by RobLoach**
Add LuaSocket to Lutro. Will allow us to make HTTP requests and download files.

### Current Status

Broken. Compiles LuaSocket, but the module is not registered in Lua.

### CODE REVIEW

**Comment by leiradel** [comment]
You should compile `wsocket.c` on Windows, and `usocket.c` on *nix. Your `Makefile` is compiling them both.

**Comment by RobLoach** [comment]
Good find...

````
deps/zlib/ioapi.o obj/./deps/zlib/unzip.o obj/./live.o -ldl deps/luajit/src/libluajit.a -lm
obj/./deps/luasocket/libluasocket/except.o: In function `except_open':
except.c:(.text+0x1ee): undefined reference to `luax_register'
obj/./deps/luasocket/libluasocket/inet.o: In function `inet_open':
inet.c:(.text+0x3c9): undefined reference to `luax_register'
obj/./deps/luasocket/libluasocket/luasocket.o: In function `luaopen_socket_core':
luasocket.c:(.text+0xb2): undefined reference to `luax_register'
obj/./deps/luasocket/libluasocket/mime.o: In function `luaopen_mime_core':
mime.c:(.text+0x1a13): undefined reference to `luax_register'
obj/./deps/luasocket/libluasocket/select.o: In function `select_open':
select.c:(.text+0x86e): undefined reference to `luax_register'
obj/./deps/luasocket/libluasocket/tcp.o:tcp.c:(.text+0x842): more undefined references to `luax_register' follow
obj/./deps/luasocket/libluasocket/unix.o: In function `luaopen_socket_unix':
unix.c:(.text+0x941): undefined reference to `luax_c_insistglobal'
collect2: error: ld returned 1 exit status
Makefile:253: recipe for target 'lutro_libretro.so' failed
make: *** [lutro_libretro.so] Error 1
```

**Comment by RobLoach** [comment]
It's compiling now, but I'd like to have a `test` in there.

**Comment by RobLoach** [comment]
Http.socket not found. Likely preloading it wrong.

**Comment by leiradel** [comment]
@RobLoach did you manage to preload the luasocket modules? If not, this recipe will embed them into the core (no need for external files) and make them available to `require`: http://hastebin.com/ticediceli.coffee

**Comment by RobLoach** [comment]
Did not manage the preload the modules. I adapted the Love code, and even yours, but still didn't figure out why it's not loading correctly. Do you know what's missing?

**Comment by Kivutar** [comment]
@leiradel variables like luasocket_src_ftp_lua contains the lua source code in a string?

@RobLoach Looks like we never invoke luaL_loadbuffer to eval the lua part of luasocket.

**Comment by leiradel** [comment]
@Kivutar yes. These names are generated by `xxd` using the path to the file used in the command line, so they could be different for your build. Open the generated header file to see what the generated name is.

**Comment by Kivutar** [comment]
I was more asking of the string contains lua code, or a path.

**Comment by leiradel** [comment]
And I've answered you!

    @leiradel variables like luasocket_src_ftp_lua contains the lua source code in a string?

    @kivutar yes.

:)

**Comment by RobLoach** [comment]
This compiles, but can't find the module when running....

```
retroarch -L lutro_libretro.so test/unit
test/unit/tests.lua:71: module 'socket.http' not found:
	no field package.preload['socket.http']
	no file './socket/http.lua'
	no file '/usr/local/share/luajit-2.0.3/socket/http.lua'
	no file '/usr/local/share/lua/5.1/socket/http.lua'
	no file '/usr/local/share/lua/5.1/socket/http/init.lua'
	no file 'test/unit/socket/http.lua'
	no file 'test/unit/socket/http/init.lua./test/socket/http.lua'
	no file './test/unit/socket/http.lua'
	no file './test/unit/luaunit/socket/http.lua'
	no file './luaunit/socket/http.lua./test/socket/http.lua'
	no file './test/unit/socket/http.lua'
	no file './test/unit/luaunit/socket/http.lua'
	no file './luaunit/socket/http.lua'
	no file './socket/http.so'
	no file '/usr/local/lib/lua/5.1/socket/http.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by Kivutar** [comment]
I'm testing it again..

**Comment by Kivutar** [comment]
Adding a printf inside __open have no effect, but a printf just before the __open call works. How come?

**Comment by Kivutar** [comment]
Renaming `__open` to `_o_open` fixed it... Don't ask me why...

    200Lutro unit test run complete

**Comment by Kivutar** [comment]
@RobLoach 

> <Alcaro> kivutar: __open is an actual function in glibc and C doesn't support function overloading.
> <Alcaro> rename to __open_luasocket. or remove underscores, why do you need them in the first place
> <Alcaro> not working for robloach (I keep reading his name as Roach and his funky smily avatar isn't helping) ... he's using another libc? he's on windows? he didn't replace every instance?

**Comment by Alcaro** [comment]
Sorry about that offhand remark about your name, didn't expect him to copypaste it. I'll just keep them to myself next time, they accomplish nothing. Rob is a beautiful name, even if it yields an unfortunate combination with Loach; you can't change your name, no matter how much I keep cross-reading the words.

**Comment by RobLoach** [comment]
> I keep reading his name as Roach and his funky smily avatar isn't helping

Clown Loach is a :fish: . Roach is something else. Back in school, some people called me [Papa Roach](https://www.youtube.com/watch?v=j0lSpNtjPM8).... Proud to be a Loach, in addition to a Rob :wink: 

> he's using another libc? he's on windows? he didn't replace every instance?

Linux, Ubuntu MATE 16.04....

```
git clone git@github.com:libretro/libretro-lutro.git lutro
cd lutro
git checkout luasocketfix
make
retroarch -L lutro_libretro.so test
[1]    7485 segmentation fault (core dumped)  retroarch -L lutro_libretro.so test
retroarch -L lutro_libretro.so test/unit
[1]    7516 segmentation fault (core dumped)  retroarch -L lutro_libretro.so test/unit
```

**Pull request merged**
