### PR TITLE
Add the OGG Mixer

### PR DESCRIPTION
**Pull request by RobLoach**
From the patch, and added the use to the test.
## Status

Not working.

### CODE REVIEW

**Comment by twinaphex** [comment]
@kivutar Any objections to this? Can this be merged or not?

**Comment by Kivutar** [comment]
We can't merge it yet. It drops wav support. It is also unable to play two ogg at the same time. And it breaks the SoundData stuff.

**Comment by Alcaro** [comment]
That ReadFile function is broken, it doesn't actually return the read data. Changing an argument doesn't propagate it back to the caller, so the allocation is lost forever.

I recommend replacing that int* buffer with an int* return value.

**Comment by Alcaro** [comment]
```
+   if (!buffer)
+   {
+      fprintf(stderr, "Memory error!");
+                                fclose(file);
+      return;
+   }
```
May want to clean up this indentation.

**Comment by twinaphex** [comment]
To all parties involved - back to the drawing board with this then I suppose?

Let's start making this an actual priority or else Lutro never gets off the ground.

**Comment by Kivutar** [comment]
Ok, the remaining tasks:

 * Modify retroluxury mixer to be able to play two ogg at the same time
 * Modify retroluxury mixer to be able to instanciate an voice before we start playing it, like it does for the wav voices. The API is not yet consistent.
 * Rework sound.c to use rl voices as data sources.
 * Rework audio.c to restaure support of rewind, stop, etc
 * Rework audio.c to be able to work with the two kind of voices: wav and ogg

**Comment by RobLoach** [comment]
> Let's start making this an actual priority or else Lutro never gets off the ground.

This and LuaSocket are the two features needed to really make Lutro awesome.

**Comment by RobLoach** [comment]
We should use the Mixer that was brought into RetorArch's menu.

**Pull request closed without merging**
