### PR TITLE
fix emscripten

### PR DESCRIPTION
**Pull request by ToadKing**
I only updated the file libretro-common code since there was some API changes in the other ones, notably RPNG.

### CODE REVIEW

**Comment by natinusala** [comment]
I'm a little late but this breaks build on Lakka : https://github.com/libretro/libretro-lutro/blob/master/libretro-common/file/file_path.c#L34

It looks like `string/stdstring.h` simply doesn't exist, maybe it's an emscripten only header?

**Comment by ToadKing** [comment]
@natinusala looks like it's a part of libretro-common https://github.com/libretro/RetroArch/blob/master/libretro-common/include/string/stdstring.h

Not sure why it builds in emscripten but not elsewhere though.

**Comment by natinusala** [comment]
Because of different include paths probably, did you add it in the makefile?

**Comment by rsn8887** [comment]
Maybe this should be reversed?

**Comment by rsn8887** [comment]
libretro-common in this repo is missing some string, encoding and other c and h files that some platforms need. But updating the all libretro-common files breaks core compilation :/

**Pull request merged**
