### PR TITLE
Fix Only FPIC

### PR DESCRIPTION
**Pull request by liberodark**

### CODE REVIEW

**Comment by twinaphex** [comment]
Unfortunately Vita fails again now.

https://git.libretro.com/libretro/libretro-lutro/-/jobs/102617

**Comment by liberodark** [comment]
@twinaphex thanks for trying again. If this is a problem, no worries I would fix it by .patch

**Comment by twinaphex** [comment]
We need a fix for this as soon as possible, yes.

**Comment by twinaphex** [comment]
@frangarcj Can you help fix things here for Vita? otherwise this keeps going back and forth.

**Comment by frangarcj** [comment]
https://github.com/libretro/libretro-lutro/pull/155

**Pull request merged**
